# Generated by Django 5.0.6 on 2024-07-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_bill_payment_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_date',
        ),
    ]
